-- MySQL Script generated by MySQL Workbench
-- Wed Sep  9 19:32:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbconsultas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbconsultas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbconsultas` ;
USE `dbconsultas` ;

-- -----------------------------------------------------
-- Table `dbconsultas`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconsultas`.`permisos` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconsultas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconsultas`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(64) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NULL,
  `telefono` VARCHAR(30) NULL,
  `tipo_doc` VARCHAR(5) NULL,
  `numero_doc` VARCHAR(20) NULL,
  `turno` VARCHAR(1) NULL COMMENT 'cargo del usuario',
  `condicion` TINYINT NOT NULL DEFAULT 1 COMMENT '1-activo, 0-inactivo',
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC))
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbconsultas`.`usuarios-permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconsultas`.`usuarios_permisos` (
  `idusuariopermiso` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idpermiso` INT NOT NULL,
  PRIMARY KEY (`idusuariopermiso`),
  INDEX `fk_idusuariopermiso_usuario_idx` (`idusuario` ASC),
  INDEX `fk_idusuariopermiso_permiso_idx` (`idpermiso` ASC),
  CONSTRAINT `fk_idusuariopermiso_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbconsultas`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idusuariopermiso_permiso`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `dbconsultas`.`permisos` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconsultas`.`tipos_consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconsultas`.`tipos_consultas` (
  `idtipoconsulta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `idpermiso` INT NOT NULL,
  PRIMARY KEY (`idtipoconsulta`),
  INDEX `fk_tipoconsulta_permiso_idx` (`idpermiso` ASC),
  CONSTRAINT `fk_tipoconsulta_permiso`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `dbconsultas`.`permisos` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbconsultas`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbconsultas`.`consultas` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `idtipoconsulta` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `fecha` DATETIME NULL,
  `estadopersona` VARCHAR(3) NULL COMMENT 'PO=positivo, NE=negativo, HV= hisopado por viajes particulares o laborales, \nHS= hisopado por cuestiones de salud, CO=contacto estrecho\n',
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `tipo_doc` VARCHAR(3) NULL,
  `numero_doc` VARCHAR(20) NULL,
  `email` VARCHAR(30) NULL,
  `telefono` VARCHAR(30) NULL,
  `estadoconsulta` VARCHAR(1) NULL COMMENT 'R=resuelta, P=pendiente, D=derivada',
  `observaciones` TEXT NULL,
  PRIMARY KEY (`idconsulta`),
  INDEX `fk_consulta_tipoconsulta_idx` (`idtipoconsulta` ASC),
  INDEX `fk_consulta_usuario_idx` (`idusuario` ASC),
  CONSTRAINT `fk_consulta_tipoconsulta`
    FOREIGN KEY (`idtipoconsulta`)
    REFERENCES `dbconsultas`.`tipos_consultas` (`idtipoconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbconsultas`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
